name: Deploy
on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-nextjs.yml@master
        with:
            process-name: tuag
        secrets: inherit
