name: Deploy

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-nextjs.yml@master
        with:
            domain: slides.bijanprogrammer.com
            base-href: /tuag/
            process-name: slides.bijanprogrammer.com_tuag
            port: 3006
        secrets: inherit
