name: Deploy

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-nextjs-export.yml@master
        with:
            domain: slides.bijanprogrammer.com
            base-href: /tuag/
        secrets: inherit
